apiVersion: v1
kind: Service
metadata:
  name: opportunities-backend
spec:
  selector:
    app: opportunities-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP 