apiVersion: apps/v1
kind: Deployment
metadata:
  name: opportunities-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opportunities-backend
  template:
    metadata:
      labels:
        app: opportunities-backend
    spec:
      containers:
      - name: backend
        image: your-registry/opportunities-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: supabase-url
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: supabase-anon-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: opportunities-backend
spec:
  selector:
    app: opportunities-backend
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP 