apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
type: Opaque
data:
  supabase-url: <base64-encoded-supabase-url>
  supabase-anon-key: <base64-encoded-supabase-anon-key>
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
type: Opaque
data:
  jwt-secret: <base64-encoded-jwt-secret> 