name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.17.0'
        cache: 'npm'
        
    - name: Install Frontend Dependencies
      run: npm install
      
    - name: Install Backend Dependencies
      run: cd backend && npm install
      
    - name: Build Frontend
      run: npm run build
      
    - name: Build Backend
      run: cd backend && npm run build
      
    - name: Run Frontend Tests
      run: npm run lint
      
    - name: Run Backend Tests
      run: cd backend && npm test 