name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.0]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Clean npm cache and node_modules
      run: |
        npm cache clean --force
        rm -rf node_modules
        rm -rf .next
    
    - name: Install dependencies
      run: |
        npm install -g npm@latest
        npm install
      
    - name: Check package versions
      run: |
        echo "Node version: $(node -v)"
        echo "NPM version: $(npm -v)"
        npm list --depth=0
    
    - name: Type check
      run: npm run type-check
    
    - name: Lint
      run: npm run lint
      
    - name: Build
      run: npm run build
      env:
        CI: true
        NODE_OPTIONS: "--max_old_space_size=4096"
    
    - name: Cache Next.js build
      uses: actions/cache@v3
      with:
        path: |
          .next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}- 